version: 1
disable_existing_loggers: False
formatters:
    basic:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

filters:
    info_special:
        (): config_logger.filters.SameLevelFilter
        'level': 'logging.INFO'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: basic
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        filters: [info_special]
        formatter: basic
        filename: info.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: basic
        filename: errors.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8

    warning_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: basic
        filename: warning.log
        maxBytes: 5242880
        backupCount: 10
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: basic
        filename: critical.log
        maxBytes: 5242880
        backupCount: 10
        encoding: utf8

loggers:
    my_logger:
        level: ERROR
        handlers: [error_file_handler, warning_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]